-- CDB$ROOT
ALTER SYSTEM SET LOCAL_LISTENER = '(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))' SCOPE=BOTH;

-- PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- xLOCAL_LISTENERiPDB
ALTER SYSTEM SET LOCAL_LISTENER = '(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))' SCOPE=BOTH;

-- REGISTER
ALTER SYSTEM REGISTER;

-- 必ずファイルの最後に書いてください
EXIT